language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - AUTOLOAD=0

script: ./build.php ${AUTOLOAD}
# after_script: ./vendor/bin/coveralls -v
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - https://www.oriskami.com/data/webhooks/travis-ci
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
